/**
 * Local source record store contract.
 *
 * Per catalog-provider-contract §"本地来源身份":
 * - the Host generates `sourceRecordId`; it never comes from a provider
 * - remote `providerId` cannot become an authoritative reference
 * - new records default to `enabled: false`; enabling is a separate user
 *   confirmation
 * - the store is the only place where the local `enabled` and `order`
 *   live — neither comes from a remote manifest
 *
 * Phase 1 ships only the interface. The concrete implementation
 * (persisting via `ctx.settings` namespace `dsh-community-market`) is M2.
 */

import type {
  AdapterId,
  LocalSourceRecord,
  ProviderId,
  SourceRecordId,
} from './types.js'

/**
 * The Host-controlled identifier factory. Phase 2 will inject a UUID
 * generator; Phase 1 uses `crypto.randomUUID()`.
 */
export type SourceRecordIdFactory = () => SourceRecordId

/**
 * Input shape for adding a source. `sourceRecordId` is generated by the
 * Host and must not be supplied by the caller.
 */
export type LocalSourceRecordInput = Omit<LocalSourceRecord, 'sourceRecordId'>

/** Result of adding a record. */
export interface AddSourceResult {
  readonly sourceRecordId: SourceRecordId
  readonly record: LocalSourceRecord
}

/**
 * Persistent, local-only store for LocalSourceRecord.
 *
 * Implementations must:
 * - persist across DSH generations (uses `ctx.settings` in M2)
 * - reject writes from network inputs (no setter accepts external JSON)
 * - keep `enabled` and `order` ownership local; never overwrite from a
 *   fetched manifest
 * - generate `sourceRecordId` server-side on `add`
 */
export interface CatalogSourceStore {
  /** Read a single record; returns undefined when not found. */
  get(sourceRecordId: SourceRecordId): LocalSourceRecord | undefined
  /** Read all records in stable order (typically by `order` asc, then `added`).`).`). */
  list(): readonly LocalSourceRecord[]
  /**
   * Insert a new record. The Host generates `sourceRecordId`; `enabled` is
   * forced to `false` regardless of caller input; the new record is
   * assigned the next available `order`.
   */
  add(input: LocalSourceRecordInput): AddSourceResult
  /**
   * Replace an existing record. `sourceRecordId` is preserved. The caller
   * may change `enabled`, `order`, and `manifestUrl` / `builtInProviderKey`
   * but cannot change `providerId` or `adapterId` (use remove + add).
   */
  update(record: LocalSourceRecord): void
  /** Remove a record. No-op if not found. */
  remove(sourceRecordId: SourceRecordId): void
}

/**
 * Validate a source record input before passing it to `Store.add. Rejects
 * records that already carry a `sourceRecordId` (callers must omit it),
 * records whose `enabled` is true (the contract forces new records to be
 * disabled), and records where `manifestUrl` and `builtInProviderKey` are
 * both set or both absent.
 */
export interface AddInputCheckResult {
  readonly ok: boolean
  readonly reason?: string
}

export function validateAddInput(input: LocalSourceRecordInput): AddInputCheckResult {
  if ('sourceRecordId' in input) {
    return { ok: false, reason: 'sourceRecordId-forbidden' }
  }
  if (input.enabled !== false) {
    return { ok: false, reason: 'enabled-must-be-false' }
  }
  const hasManifestUrl = input.manifestUrl !== undefined
  const hasBuiltInKey = input.builtInProviderKey !== undefined
  if (hasManifestUrl === hasBuiltInKey) {
    return { ok: false, reason: 'manifest-or-built-in-required' }
  }
  return { ok: true }
}

/**
 * Helper used by both Phase 2 implementation and Phase 1 test fixtures:
 * compose a fresh record by combining the Host-generated UUID with the
 * validated input.
 */
export function composeLocalSourceRecord(
  input: LocalSourceRecordInput,
  sourceRecordId: SourceRecordId,
): LocalSourceRecord {
  return {
    sourceRecordId,
    registrationKind: input.registrationKind,
    adapterId: input.adapterId,
    providerId: input.providerId,
    manifestUrl: input.manifestUrl,
    builtInProviderKey: input.builtInProviderKey,
    enabled: false,
    order: input.order,
  }
}

/** Default UUID factory backed by Node 22's `crypto.randomUUID()`. */
export const defaultSourceRecordIdFactory: SourceRecordIdFactory = () => {
  // crypto is a global in Node 19+; we keep the cast so types stay portable.
  return (globalThis.crypto as { randomUUID(): string }).randomUUID() as SourceRecordId
}

/**
 * Validate that a record's identifying fields are coherent.
 *
 * Used by `update` to reject mutations that try to silently change the
 * adapter or provider binding (those require remove + add).
 */
export function validateRecordCoherence(record: LocalSourceRecord): AddInputCheckResult {
  const hasManifestUrl = record.manifestUrl !== undefined
  const hasBuiltInKey = record.builtInProviderKey !== undefined
  if (hasManifestUrl === hasBuiltInKey) {
    return { ok: false, reason: 'manifest-or-built-in-required' }
  }
  if (record.registrationKind === 'user-added' && !hasManifestUrl) {
    return { ok: false, reason: 'user-added-needs-manifestUrl' }
  }
  if (record.registrationKind === 'built-in' && !hasBuiltInKey) {
    return { ok: false, reason: 'built-in-needs-builtInProviderKey' }
  }
  return { ok: true }
}

/** Re-exported identity types for store callers. */
export type { AdapterId, LocalSourceRecord, ProviderId, SourceRecordId }