/**
 * TypeScript contract types for the DSH Community Market.
 *
 * Hand-written mirrors of the four catalog schemas in docs/schemas/ plus the
 * `LocalSourceRecord` shape defined in catalog-provider-contract §"本地来源身份".
 *
 * These types are deliberately structural — they describe what the schemas
 * accept, not what JSON Schema can statically prove. Format and pattern
 * constraints (uri, date-time, uuid, BCP 47, no control characters) are
 * enforced by ajv at runtime; TypeScript only enforces shape.
 *
 * If a schema changes, update the corresponding type here. The vitest suite
 * checks that canonical fixtures satisfy these types — typecheck failure is
 * the earliest signal of drift.
 */

/** A source-manifest provider claim; not a local authoritative identity. */
export type ProviderId = string

/** Stable local adapter identifier (e.g. 'market.standard-v1'). */
export type AdapterId = string

/** Host-generated opaque UUID; the local authoritative identity for a source. */
export type SourceRecordId = string

/**
 * Locally-owned record of a registered catalog source.
 *
 * Generated by the Host. Never serialized from a remote manifest or response.
 * See catalog-provider-contract §"本地来源身份".
 */
export interface LocalSourceRecord {
  /** Host-generated opaque UUID. The local authoritative identity. */
  sourceRecordId: SourceRecordId
  /** User-added manifest URL vs built-in adapter. */
  registrationKind: 'user-added' | 'built-in'
  /** Stable local adapter ID. */
  adapterId: AdapterId
  /** Provider-claimed ID. Not authoritative; never used for trust decisions. */
  providerId: ProviderId
  /** Set when registrationKind is 'user-added'. Mutually exclusive with builtInProviderKey. */
  manifestUrl?: string
  /** Set when registrationKind is 'built-in'. Mutually exclusive with manifestUrl. */
  builtInProviderKey?: string
  /** Whether the source is enabled. New records default to false. */
  enabled: boolean
  /** Display order. Lower numbers come first. Order only affects display. */
  order: number
}

/** Fields the catalog query schema accepts. */
export type CatalogQueryField =
  | 'q'
  | 'category'
  | 'capability'
  | 'cursor'
  | 'limit'
  | 'sort'
  | 'locale'

/** Sort values the catalog source manifest can advertise. */
export type CatalogQuerySort = 'relevance' | 'updated' | 'name' | 'downloads'

/** Static source manifest published by a standard catalog provider. */
export interface CatalogSourceManifest {
  manifestVersion: '1.0.0'
  providerId: ProviderId
  name: string
  description?: string
  homepage?: string
  attribution: {
    name: string
    url: string
    notice?: string
  }
  transport: {
    kind: 'https-json'
    endpoint: string
    method: 'GET'
  }
  query: {
    supported: readonly CatalogQueryField[]
    defaultLimit: number
    maxLimit: number
    sorts: readonly CatalogQuerySort[]
  }
}

/** Normalized catalog query accepted by every CatalogAdapter. */
export interface CatalogQuery {
  q?: string
  category?: readonly string[]
  capability?: readonly string[]
  cursor?: string
  limit?: number
  sort?: CatalogQuerySort
  locale?: string
}

/** npm registry package identity. */
export interface NpmPackage {
  registry: 'npm'
  name: string
}

/** Repository identity with optional subdirectory. */
export interface Repository {
  url: string
  subdirectory?: string
}

/** Plugin publisher claim. */
export interface PluginPublisher {
  name: string
  url?: string
}

/** Plugin capability declarations. */
export interface PluginCapabilityList {
  required?: readonly string[]
  optional?: readonly string[]
}

/** Plugin compatibility declarations. */
export interface PluginCompatibility {
  apiVersion?: string
  hosts?: readonly string[]
}

/**
 * Item shape in a provider page (untrusted wire response; no Host provenance).
 *
 * The schema requires either `repository` or `package` (anyOf). TypeScript
 * cannot express `anyOf` cleanly, so both fields are listed as optional and
 * the runtime validator enforces the disjunction.
 */
export interface CatalogProviderPageItem {
  id: string
  name: string
  displayName: string
  summary: string
  description?: string
  homepage?: string
  latestVersion?: string
  license?: string
  categories?: readonly string[]
  keywords?: readonly string[]
  repository?: Repository
  package?: NpmPackage
  publisher?: PluginPublisher
  capabilities?: PluginCapabilityList
  compatibility?: PluginCompatibility
  updatedAt?: string
}

/** Standard HTTPS provider page. Untrusted; provenance is injected by the Host. */
export interface CatalogProviderPage {
  schemaVersion: '1.0.0'
  generatedAt?: string
  revision?: string
  items: readonly CatalogProviderPageItem[]
  page: {
    nextCursor?: string
    total?: number
  }
}

/** Snapshot item with required Host-injected provenance. */
export interface CatalogSnapshotItem extends Omit<CatalogProviderPageItem, 'provenance'> {
  provenance: {
    sourceRecordId: SourceRecordId
    providerId: ProviderId
    itemId: string
  }
}

/** Host-observed source identity that decorates a normalized snapshot. */
export interface CatalogSnapshotSource {
  sourceRecordId: SourceRecordId
  providerId: ProviderId
  adapterId: AdapterId
  registrationKind: 'user-added' | 'built-in'
  fetchedAt: string
  finalUrl: string
  providerGeneratedAt?: string
  providerRevision?: string
}

/**
 * Normalized catalog snapshot, the only data structure the UI and the
 * install candidate resolver consume. The Host-observed provenance field
 * is required on every item.
 */
export interface CatalogSnapshot {
  schemaVersion: '1.0.0'
  source: CatalogSnapshotSource
  items: readonly CatalogSnapshotItem[]
  page: {
    nextCursor?: string
    total?: number
  }
}